name: check-go-coverage

on:
  pull_request:
    branches: [master]

jobs:
  coverage:
    name: generate-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go 1.20.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Run test metrics script
        id: testcov
        run: |
          echo "coverage = make test-coverage-report | tee test-results" >> $GITHUB_OUTPUT
          TOTAL_TESTS=$(cat test-results | grep -v TestQueriesContent/ | grep -v TestQueriesMetadata/ | grep -v TestQueries/ | grep PASS | wc -l)
          echo "Total Tests :: ${TOTAL_TESTS}"
          echo "::set-output name=total_tests::${TOTAL_TESTS}"
      - name: Checks if Go coverage is at least 80%
        run: |
          echo "Total Tests :: ${{ steps.testcov.outputs.coverage }}"