name: KICS Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  kics_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create results directory
        run: mkdir -p results-dir

      - name: Run KICS Scan
        uses: Checkmarx/kics-github-action@latest
        with:
          path: 'terraform'
          output_path: results-dir

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results-dir/results.sarif
